[theme]
primaryColor = "#eb5f34ff"
backgroundColor = "#505058ff"
secondaryBackgroundColor = "#494957ff"
textColor = "#e6e4dfff"
font = "monospace"

[theme.sidebar]
backgroundColor = "#494957ff"
textColor = "#cacae4ff"
menuBackgroundColor = "#444444"
font = "monospace"